In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from pandas import DataFrame as df

In [51]:
iris= datasets.load_iris()
X= iris.data
Y=iris.target
print(X.shape)
X= np.insert(X,X.shape[1], Y, axis=1)
data= pd.DataFrame(X)

data=data.reindex(np.random.permutation(data.index))
data.head()

(150, 4)


0    1    2    3    4
39   5.1  3.4  1.5  0.2  0.0
25   5.0  3.0  1.6  0.2  0.0
116  6.5  3.0  5.5  1.8  2.0
68   6.2  2.2  4.5  1.5  1.0
5    5.4  3.9  1.7  0.4  0.0

In [20]:

print(X.shape)
print(Y.shape)

(150, 5)
(150,)


In [52]:
#input layer will have 4 nodes and output layer will have 3 nodes(the 4th column is classifies into 0,1 and 2 . hence 3)
features = data.iloc[:,:4]
target = data.iloc[:,4]

target = target.values.reshape((target.shape[0],1))
target_class= np.zeros(shape=(target.shape[0],3))

for i in range(target.shape[0]):
    if target[i] == 0:
        target_class[i][0]=1
    elif target[i]==1:
        target_class[i][1]=1
    else:
        target_class[i][2]=1
print(target_class.shape)
print(target.shape)


(150, 3)
(150, 1)


In [53]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))
def der_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

In [54]:
input_nodes = features.shape[1]
output_nodes=3
weight_matrix= np.random.uniform(size=(input_nodes,output_nodes))
epoch=1000
lr=0.02

In [55]:
for i in range(epoch):
    output_node_input = features.dot(weight_matrix)
    output= sigmoid(output_node_input)
    
    error = target_class - output
    drv = der_sigmoid(output_node_input)
    delta_weight = error*drv
    
    weight_matrix = weight_matrix + lr*features.T.dot(delta_weight)

In [56]:
final_output = np.array(output)
#print(final_output)
output_class = np.zeros(shape  = final_output.shape[0])

for i in range(final_output.shape[0]):
    output_class[i] = np.argmax(final_output[i])
print(output_class)
class_diff = output_class - target[:,0]

[0. 0. 2. 1. 0. 0. 0. 2. 1. 1. 0. 2. 0. 0. 2. 0. 1. 2. 0. 0. 1. 0. 1. 0.
 2. 2. 2. 0. 1. 1. 0. 1. 2. 2. 2. 1. 0. 2. 1. 1. 1. 1. 0. 0. 2. 2. 2. 1.
 1. 1. 0. 1. 2. 2. 0. 0. 2. 2. 0. 0. 0. 0. 0. 1. 2. 1. 2. 2. 1. 0. 2. 2.
 1. 0. 2. 1. 0. 1. 2. 2. 0. 1. 2. 0. 2. 0. 0. 2. 1. 1. 0. 2. 1. 1. 1. 2.
 0. 2. 0. 2. 2. 2. 1. 1. 1. 0. 2. 1. 1. 1. 1. 0. 2. 2. 0. 2. 0. 1. 0. 2.
 0. 2. 2. 2. 0. 1. 2. 2. 2. 1. 0. 1. 2. 0. 1. 2. 2. 0. 0. 2. 2. 2. 0. 1.
 1. 2. 0. 2. 0. 1.]


In [45]:
print(target_class)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1.

In [46]:
print(class_diff)

[ 0.  0. -2.  0.  1.  1. -2. -1. -1.  1. -1.  0. -1.  0. -1.  0. -1.  1.
  1.  0.  0.  1. -1.  1.  0.  1.  1.  0. -1. -2.  1. -1. -2. -1.  1. -1.
 -1.  0.  0.  0. -1. -1. -1.  1.  1. -1.  1.  1.  1.  0.  0. -1. -2. -1.
  0.  0. -1. -2.  0. -1. -1.  0.  1.  0. -1. -1. -2.  0. -1.  1.  0. -1.
  0.  1. -2.  0. -1.  0. -2.  0. -2. -2. -1.  0. -1. -1. -1.  1. -1.  0.
 -1.  0. -1. -1. -2. -1. -2. -1.  1.  1. -1.  0. -1. -1.  1.  1. -1.  1.
  0.  1. -1.  0.  0.  1.  1. -1.  0.  1. -2.  1.  1. -1. -1. -1.  0.  0.
 -1.  1.  0. -1.  0. -2.  0.  0.  0.  1.  0.  1.  0. -1. -2.  0.  1. -1.
  0. -1. -1. -1.  0. -1.]


In [57]:
print('Actual class')
print(target[:,0])
print('>>>>>>>>>>>>>>>>>>>>>>>>')
print('Predicted class')
print(output_class)

wrong_prediction = np.count_nonzero(class_diff)
N= len(class_diff)
simple_accuracy = 100*(N-wrong_prediction)/N
print('Accuracy:-',(simple_accuracy),'%')

Actual class
[0. 0. 2. 1. 0. 0. 0. 2. 1. 1. 0. 2. 0. 0. 2. 0. 1. 2. 0. 0. 1. 0. 1. 0.
 2. 1. 2. 0. 1. 1. 0. 1. 2. 2. 2. 1. 0. 2. 1. 1. 1. 1. 0. 0. 2. 2. 2. 1.
 1. 1. 0. 1. 2. 1. 0. 0. 2. 2. 0. 0. 0. 0. 0. 1. 2. 1. 2. 2. 1. 0. 2. 2.
 1. 0. 2. 2. 0. 1. 2. 2. 0. 1. 2. 0. 2. 0. 0. 2. 1. 1. 0. 2. 1. 1. 1. 2.
 0. 1. 0. 2. 2. 2. 1. 1. 1. 0. 2. 1. 1. 1. 1. 0. 2. 2. 0. 2. 0. 1. 0. 1.
 0. 2. 2. 1. 0. 1. 2. 1. 2. 1. 0. 1. 2. 0. 1. 2. 2. 0. 0. 2. 2. 2. 0. 1.
 1. 2. 0. 2. 0. 1.]
>>>>>>>>>>>>>>>>>>>>>>>>
Predicted class
[0. 0. 2. 1. 0. 0. 0. 2. 1. 1. 0. 2. 0. 0. 2. 0. 1. 2. 0. 0. 1. 0. 1. 0.
 2. 2. 2. 0. 1. 1. 0. 1. 2. 2. 2. 1. 0. 2. 1. 1. 1. 1. 0. 0. 2. 2. 2. 1.
 1. 1. 0. 1. 2. 2. 0. 0. 2. 2. 0. 0. 0. 0. 0. 1. 2. 1. 2. 2. 1. 0. 2. 2.
 1. 0. 2. 1. 0. 1. 2. 2. 0. 1. 2. 0. 2. 0. 0. 2. 1. 1. 0. 2. 1. 1. 1. 2.
 0. 2. 0. 2. 2. 2. 1. 1. 1. 0. 2. 1. 1. 1. 1. 0. 2. 2. 0. 2. 0. 1. 0. 2.
 0. 2. 2. 2. 0. 1. 2. 2. 2. 1. 0. 1. 2. 0. 1. 2. 2. 0. 0. 2. 2. 2. 0. 1.
 1. 2. 0. 2. 0. 1.]
Accuracy:- 95.33333333333333 %