In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

/home/manisha/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
#tensor that contains a constant value 2
t1= tf.constant(2.0,dtype=tf.float32)

In [3]:
print(t1)
#prints tensor objct that says its name of tensor as Const:0 this is assigned by tensorflow 
#unless u mention what the name is going to be using name keyword
#by printing tensor we don't get value but tensor
#to get value we need sessions

Tensor("Const:0", shape=(), dtype=float32)


In [5]:
t1= tf.constant(2.0,dtype=tf.float32, name='my_first_tensor')
t1
#dtype says the type of tensor
#tf.constant- allows tensor to have constant value

<tf.Tensor 'my_first_tensor_1:0' shape=() dtype=float32>

In [6]:
t2= tf.constant([1.0, 2.0],dtype=tf.float32, name='tensor2')
print(t2)

Tensor("tensor2:0", shape=(2,), dtype=float32)


In [8]:
#tf.Session gives a session object. When u call run() on that object and pass it a tensor object,
#it return value of that tensor
sess= tf.Session()
print(sess.run(t1)) #executing sesssion

2.0


In [9]:
sess.run(t2)

array([1., 2.], dtype=float32)

In [10]:
t3= tf.constant([[1.0,2.0,3.0],
                [5.0,6.0,7.0]],dtype= tf.float32, name='tensor3')
print(sess.run(t3))
print(t3)

[[1. 2. 3.]
 [5. 6. 7.]]
Tensor("tensor3:0", shape=(2, 3), dtype=float32)


In [12]:
sess.close()
#after using session, close it

In [13]:
#use session like this and no need to manually close it
with tf.Session() as sess:
    print(sess.run(t1))
    print(sess.run(t2))
    print(sess.run(t3))

2.0
[1. 2.]
[[1. 2. 3.]
 [5. 6. 7.]]


In [ ]:
#Building Computational graph
cg1=tf.graph()